[project]
name = "go-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "dowhy>=0.14",
    "econml>=0.17.0",
    "numba>=0.67.0",
    "numpy>=1.24",
    "pyupgrade>=3.21.2",
    "ruff>=0.16.7",
    "scikit-learn>=1.9.1",
    "scipy>=1.18.1",
    "tigramite>=5.2.10.1",
]
